sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION != "5.4" ]]; then composer install; fi
  - if [[ $TRAVIS_PHP_VERSION = "5.4" ]]; then composer require satooshi/php-coveralls; fi

script:
  - mkdir -p build/logs
  - if [[ $TRAVIS_PHP_VERSION != "5.4" ]]; then vendor/bin/phpunit; fi
  - if [[ $TRAVIS_PHP_VERSION = "5.4" ]]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" = "5.4" ]]; then php vendor/bin/coveralls -v; fi
